from __future__ import annotations

import json
import shutil
from pathlib import Path

from ose_library_wb import core


FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "min_library"


def _copy_fixture_library(tmp_path: Path) -> Path:
    """Copy the fixture library into tmp_path so validation writes (reports/)
    never touch the tracked fixture tree."""

    dest = tmp_path / "min_library"
    shutil.copytree(FIXTURE_ROOT, dest)
    return dest


class DummyDoc:
    def __init__(self):
        self.Objects = []

    def addObject(self, type_name, label):
        obj = DummyObject(type_name, label)
        self.Objects.append(obj)
        return obj


class DummyObject:
    def __init__(self, type_name, label):
        self.Type = type_name
        self.Label = label


def test_open_library_minimal_fixture():
    entries = core.open_library(FIXTURE_ROOT)

    assert [entry.id for entry in entries] == ["mini_box"]
    assert entries[0].layer == "module"


def test_compile_entry_merges_schema_override():
    entry = core.open_library(FIXTURE_ROOT)[0]
    doc = DummyDoc()

    created = core.compile_entry_into(
        entry,
        doc,
        {"width_in": 8, "nested": {"label": "wide_box"}},
    )

    assert created == doc.Objects
    assert created[0].Width == 8
    assert created[0].Label == "wide_box"
    assert created[0].Enabled is True


def test_export_schema_new(tmp_path):
    entry = core.open_library(FIXTURE_ROOT)[0]
    target_entry = entry.__class__(
        id=entry.id,
        layer=entry.layer,
        path=tmp_path,
        meta=entry.meta,
        expect=entry.expect,
        schema_path=tmp_path / "schema.py",
        compiler_path=entry.compiler_path,
        status=entry.status,
    )

    path = core.export_schema_new(target_entry, {"schema_name": "edited", "width_in": 9})

    assert path == tmp_path / "schema.py.new"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# Generated by OSE Library Workbench v0.")
    assert "'width_in': 9" in text


def test_validate_live_writes_combined_report(tmp_path):
    library_root = _copy_fixture_library(tmp_path)
    entry = core.open_library(library_root)[0]
    doc = DummyDoc()
    core.compile_entry_into(entry, doc)

    report = core.validate_live(entry, doc)

    assert report.tier == "code+output"
    check_names = [check.name for check in report.checks]
    assert any(name.startswith("code:") for name in check_names)
    assert any(name.startswith("output:") for name in check_names)
    assert "code:schema_data_only" in check_names

    # No real FreeCAD shapes are available under the DummyDoc, so the
    # output-tier completeness check (expect.yaml requires >=1 solid) is
    # expected to fail — this proves the tier-2 path runs end to end even
    # headless, not that geometry is actually validated.
    output_checks = {check.name: check for check in report.checks if check.name.startswith("output:")}
    assert output_checks["output:completeness"].passed is False
    assert report.passed is False

    report_path = library_root / "reports" / "mini_box.json"
    assert report_path.is_file()
    written = json.loads(report_path.read_text(encoding="utf-8"))
    assert written["id"] == "mini_box"
    assert written["tier"] == "code+output"
    assert written["passed"] is False
