from __future__ import annotations

from copy import deepcopy
import json
import sys
from types import ModuleType

import pytest
import shutil
from pathlib import Path

from ose_library_wb import core


FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "min_library"


def _copy_fixture_library(tmp_path: Path) -> Path:
    """Copy the fixture library into tmp_path so validation writes (reports/)
    never touch the tracked fixture tree."""

    dest = tmp_path / "min_library"
    shutil.copytree(FIXTURE_ROOT, dest)
    return dest


class DummyDoc:
    def __init__(self):
        self.Objects = []
        self.UndoMode = 0

    def addObject(self, type_name, label):
        name = label
        while self.getObject(name) is not None:
            name += "_new"
        obj = DummyObject(type_name, label)
        obj.Name = name
        self.Objects.append(obj)
        return obj


    def getObject(self, name):
        return next((obj for obj in self.Objects if obj.Name == name), None)

    def removeObject(self, name):
        self.Objects.remove(self.getObject(name))

    def recompute(self):
        pass

    def openTransaction(self, name):
        self._snapshot = ([(obj, deepcopy(obj.__dict__)) for obj in self.Objects]
                          if self.UndoMode else None)

    def commitTransaction(self):
        self._snapshot = None

    def abortTransaction(self):
        if self._snapshot is None:
            return
        self.Objects = [obj for obj, _ in self._snapshot]
        for obj, values in self._snapshot:
            obj.__dict__.clear()
            obj.__dict__.update(values)
        self._snapshot = None


class DummyObject:
    def __init__(self, type_name, label):
        self.Type = type_name
        self.Label = label

    def addProperty(self, *args):
        pass

    def setEditorMode(self, *args):
        pass


def test_open_library_minimal_fixture():
    entries = core.open_library(FIXTURE_ROOT)

    assert [entry.id for entry in entries] == ["mini_box"]
    assert entries[0].layer == "module"


def test_compile_entry_merges_schema_override():
    entry = core.open_library(FIXTURE_ROOT)[0]
    doc = DummyDoc()

    created = core.compile_entry_into(
        entry,
        doc,
        {"width_in": 8, "nested": {"label": "wide_box"}},
    )

    assert created == doc.Objects
    assert created[0].Width == 8
    assert created[0].Label == "wide_box"
    assert created[0].Enabled is True


def test_export_schema_new(tmp_path):
    entry = core.open_library(FIXTURE_ROOT)[0]
    target_entry = entry.__class__(
        id=entry.id,
        layer=entry.layer,
        path=tmp_path,
        meta=entry.meta,
        expect=entry.expect,
        schema_path=tmp_path / "schema.py",
        compiler_path=entry.compiler_path,
        status=entry.status,
    )

    path = core.export_schema_new(target_entry, {"schema_name": "edited", "width_in": 9})

    assert path == tmp_path / "schema.py.new"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# Generated by OSE Library Workbench v0.")
    assert "'width_in': 9" in text


def test_validate_live_writes_combined_report(tmp_path):
    library_root = _copy_fixture_library(tmp_path)
    entry = core.open_library(library_root)[0]
    doc = DummyDoc()
    core.compile_entry_into(entry, doc)

    report = core.validate_live(entry, doc)

    assert report.tier == "code+output"
    check_names = [check.name for check in report.checks]
    assert any(name.startswith("code:") for name in check_names)
    assert any(name.startswith("output:") for name in check_names)
    assert "code:schema_data_only" in check_names

    # No real FreeCAD shapes are available under the DummyDoc, so the
    # output-tier completeness check (expect.yaml requires >=1 solid) is
    # expected to fail — this proves the tier-2 path runs end to end even
    # headless, not that geometry is actually validated.
    output_checks = {check.name: check for check in report.checks if check.name.startswith("output:")}
    assert output_checks["output:completeness"].passed is False
    assert report.passed is False

    report_path = library_root / "reports" / "mini_box.json"
    assert report_path.is_file()
    written = json.loads(report_path.read_text(encoding="utf-8"))
    assert written["id"] == "mini_box"
    assert written["tier"] == "code+output"
    assert written["passed"] is False


@pytest.mark.parametrize("runtime", [False, True])
def test_collection_helpers_are_scoped_across_library_switches(tmp_path, monkeypatch, runtime):
    # Simulate another plugin already using an identically named module.
    original = ModuleType("shared_geometry")
    original.VALUE = "plugin"
    monkeypatch.setitem(sys.modules, "shared_geometry", original)
    previous_path = sys.path[:]
    entries = []
    for index in range(2):
        root = tmp_path / str(index) / "collections" / "gvcs"
        shutil.copytree(FIXTURE_ROOT, root)
        (root / "shared_geometry.py").write_text(f"VALUE = {index}\n")
        entry = core.open_library(root)[0]
        entry.compiler_path.write_text(
            ("" if runtime else "from shared_geometry import VALUE\n")
            + "def compile(schema, doc):\n"
            + ("    from shared_geometry import VALUE\n" if runtime else "")
            + "    obj = doc.addObject('Part::Feature', 'Result')\n"
            + "    obj.Value = VALUE\n"
            + "    return [obj]\n"
        )
        entries.append(entry)
    for index in [0, 1, 0]:
        result = core.compile_entry_into(entries[index], DummyDoc())
        assert result[0].Value == index
        assert sys.modules["shared_geometry"] is original
        assert sys.path == previous_path


def test_failed_compile_restores_import_state(tmp_path):
    root = _copy_fixture_library(tmp_path)
    entry = core.open_library(root)[0]
    (root / "entry_test_helper.py").write_text("VALUE = 1\n")
    entry.compiler_path.write_text(
        "def compile(schema, doc):\n"
        "    import entry_test_helper\n"
        "    raise RuntimeError('compile failed')\n"
    )
    previous_path = sys.path[:]
    with pytest.raises(RuntimeError, match="compile failed"):
        core.compile_entry_into(entry, DummyDoc())
    assert sys.path == previous_path
    assert "entry_test_helper" not in sys.modules


def test_managed_replacement_preserves_unrelated_objects_and_schema():
    entry = core.open_library(FIXTURE_ROOT)[0]
    doc = DummyDoc()
    unrelated = doc.addObject("Part::Box", "UserGeometry")
    original = core.compile_managed_entry(entry, doc)
    replacement = core.replace_managed_entry(entry, doc, {"width_in": 9})
    binding = core.require_managed_entry(entry, doc)

    assert unrelated in doc.Objects
    assert original[0] not in doc.Objects
    assert len(doc.Objects) == 3  # user's box, replacement box, saved binding
    assert replacement[0].Width == 9
    assert replacement[0].Name == original[0].Name
    assert replacement[0].Label == original[0].Label
    assert doc.UndoMode == 0
    assert binding.ManagedNames == [replacement[0].Name]
    assert core.managed_schema_override(entry, doc)["width_in"] == 9
    with pytest.raises(ValueError, match="already has"):
        core.compile_managed_entry(entry, doc)


def test_failed_replacement_rolls_back_partial_geometry_and_binding(tmp_path):
    root = _copy_fixture_library(tmp_path)
    entry = core.open_library(root)[0]
    doc = DummyDoc()
    core.compile_managed_entry(entry, doc, {"width_in": 7})
    before_objects = doc.Objects[:]
    before_schema = core.managed_schema_override(entry, doc)
    entry.compiler_path.write_text(
        "def compile(schema, doc):\n"
        "    doc.addObject('Part::Box', 'Partial')\n"
        "    raise RuntimeError('after partial geometry')\n"
    )
    with pytest.raises(RuntimeError, match="partial geometry"):
        core.replace_managed_entry(entry, doc, {"width_in": 12})
    assert doc.Objects == before_objects
    assert core.managed_schema_override(entry, doc) == before_schema
    assert doc.UndoMode == 0


def test_initial_compile_failure_leaves_unrelated_objects(tmp_path):
    root = _copy_fixture_library(tmp_path)
    entry = core.open_library(root)[0]
    doc = DummyDoc()
    unrelated = doc.addObject("Part::Box", "UserGeometry")
    entry.compiler_path.write_text(
        "def compile(schema, doc):\n"
        "    obj = doc.addObject('Part::Feature', 'Broken')\n"
        "    obj.State = ['Invalid']\n"
        "    return [obj]\n"
    )
    with pytest.raises(ValueError, match="invalid object"):
        core.compile_managed_entry(entry, doc)
    assert doc.Objects == [unrelated]


def test_document_identity_survives_reopen_and_rejects_other_checkout(tmp_path):
    entry = core.open_library(FIXTURE_ROOT)[0]
    other = core.open_library(_copy_fixture_library(tmp_path))[0]
    doc = DummyDoc()
    core.compile_managed_entry(entry, doc)
    reopened = deepcopy(doc)  # no Python-side document registry needed
    core.require_managed_entry(entry, reopened)
    with pytest.raises(ValueError, match="different library entry"):
        core.replace_managed_entry(other, reopened)
    with pytest.raises(ValueError, match="different library entry"):
        core.validate_managed_entry(other, reopened)
    with pytest.raises(ValueError, match="not an OSE entry"):
        core.require_managed_entry(entry, DummyDoc())
    with pytest.raises(ValueError, match="Compile the selected"):
        core.require_managed_entry(entry, None)


def test_managed_validation_excludes_unrelated_geometry(monkeypatch):
    entry = core.open_library(FIXTURE_ROOT)[0]
    doc = DummyDoc()
    doc.addObject("Part::Box", "UserGeometry")
    created = core.compile_managed_entry(entry, doc)
    received = []

    def validate(selected, objects):
        assert selected is entry
        received.extend(objects.Objects)
        return "report"

    monkeypatch.setattr(core, "validate_live", validate)
    assert core.validate_managed_entry(entry, doc) == "report"
    assert received == created


def test_deleted_managed_geometry_is_rejected():
    entry = core.open_library(FIXTURE_ROOT)[0]
    doc = DummyDoc()
    created = core.compile_managed_entry(entry, doc)
    doc.removeObject(created[0].Name)
    with pytest.raises(ValueError, match="incomplete"):
        core.require_managed_entry(entry, doc)



def test_managed_compile_preserves_enabled_undo_mode():
    entry = core.open_library(FIXTURE_ROOT)[0]
    doc = DummyDoc()
    doc.UndoMode = 1
    core.compile_managed_entry(entry, doc)
    core.replace_managed_entry(entry, doc, {"width_in": 9})
    assert doc.UndoMode == 1
