from __future__ import annotations

from pathlib import Path

from ose_library_wb import core


FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "min_library"


class DummyDoc:
    def __init__(self):
        self.Objects = []

    def addObject(self, type_name, label):
        obj = DummyObject(type_name, label)
        self.Objects.append(obj)
        return obj


class DummyObject:
    def __init__(self, type_name, label):
        self.Type = type_name
        self.Label = label


def test_open_library_minimal_fixture():
    entries = core.open_library(FIXTURE_ROOT)

    assert [entry.id for entry in entries] == ["mini_box"]
    assert entries[0].layer == "module"


def test_compile_entry_merges_schema_override():
    entry = core.open_library(FIXTURE_ROOT)[0]
    doc = DummyDoc()

    created = core.compile_entry_into(
        entry,
        doc,
        {"width_in": 8, "nested": {"label": "wide_box"}},
    )

    assert created == doc.Objects
    assert created[0].Width == 8
    assert created[0].Label == "wide_box"
    assert created[0].Enabled is True


def test_export_schema_new(tmp_path):
    entry = core.open_library(FIXTURE_ROOT)[0]
    target_entry = entry.__class__(
        id=entry.id,
        layer=entry.layer,
        path=tmp_path,
        meta=entry.meta,
        expect=entry.expect,
        schema_path=tmp_path / "schema.py",
        compiler_path=entry.compiler_path,
        status=entry.status,
    )

    path = core.export_schema_new(target_entry, {"schema_name": "edited", "width_in": 9})

    assert path == tmp_path / "schema.py.new"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# Generated by OSE Library Workbench v0.")
    assert "'width_in': 9" in text
